apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-api
  template:
    metadata:
      labels:
        app: visits-api
    spec:
      containers:
        - name: visits-api
          image: <your-account-id>.dkr.ecr.<region>.amazonaws.com/visits-api:latest
          # example:
          # image: 123456789012.dkr.ecr.us-west-1.amazonaws.com/visits-api:latest
          ports:
            - containerPort: 80
